# SPRING CONFIG
spring:
  data:
    mongodb:
      uri: jdbc:mysql://localhost:3306/book
      database: book
  #      collection:
  #        info-ekyc: info_ekyc
  #        info-ekyc-history: info_ekyc_history
  #        info-ekyc-status: info_ekyc_status
  #        info-appointment: ekyc_appointment_info
  #        info-ekyc-contract: ekyc_contract_info
  #        info-ekyc-meeting: ekyc_meeting_info
  #        contract-status-response: contract_status_response
  #    DATASOURCE MARIADB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 2911

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  redis:
#    host: redis
#    port: 6379
#    database: 0
#    password: admin123